services:
  backend:
    build: ./backend
    container_name: netbank-backend
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: netbank-frontend
    ports:
      - "8081:80"
    depends_on:
      - backend